# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, author_id=None, title=None, description=None, ingredients=None, instructions=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param author_id: The author_id of this InlineObject.  # noqa: E501
        :type author_id: int
        :param title: The title of this InlineObject.  # noqa: E501
        :type title: str
        :param description: The description of this InlineObject.  # noqa: E501
        :type description: str
        :param ingredients: The ingredients of this InlineObject.  # noqa: E501
        :type ingredients: List[str]
        :param instructions: The instructions of this InlineObject.  # noqa: E501
        :type instructions: str
        """
        self.openapi_types = {
            'author_id': int,
            'title': str,
            'description': str,
            'ingredients': List[str],
            'instructions': str
        }

        self.attribute_map = {
            'author_id': 'author_id',
            'title': 'title',
            'description': 'description',
            'ingredients': 'ingredients',
            'instructions': 'instructions'
        }

        self._author_id = author_id
        self._title = title
        self._description = description
        self._ingredients = ingredients
        self._instructions = instructions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author_id(self):
        """Gets the author_id of this InlineObject.


        :return: The author_id of this InlineObject.
        :rtype: int
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """Sets the author_id of this InlineObject.


        :param author_id: The author_id of this InlineObject.
        :type author_id: int
        """

        self._author_id = author_id

    @property
    def title(self):
        """Gets the title of this InlineObject.


        :return: The title of this InlineObject.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineObject.


        :param title: The title of this InlineObject.
        :type title: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this InlineObject.


        :return: The description of this InlineObject.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineObject.


        :param description: The description of this InlineObject.
        :type description: str
        """

        self._description = description

    @property
    def ingredients(self):
        """Gets the ingredients of this InlineObject.


        :return: The ingredients of this InlineObject.
        :rtype: List[str]
        """
        return self._ingredients

    @ingredients.setter
    def ingredients(self, ingredients):
        """Sets the ingredients of this InlineObject.


        :param ingredients: The ingredients of this InlineObject.
        :type ingredients: List[str]
        """

        self._ingredients = ingredients

    @property
    def instructions(self):
        """Gets the instructions of this InlineObject.


        :return: The instructions of this InlineObject.
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this InlineObject.


        :param instructions: The instructions of this InlineObject.
        :type instructions: str
        """

        self._instructions = instructions
