# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, comment_id=None, user_id=None, text=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param comment_id: The comment_id of this InlineResponse2002.  # noqa: E501
        :type comment_id: int
        :param user_id: The user_id of this InlineResponse2002.  # noqa: E501
        :type user_id: int
        :param text: The text of this InlineResponse2002.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'comment_id': int,
            'user_id': int,
            'text': str
        }

        self.attribute_map = {
            'comment_id': 'comment_id',
            'user_id': 'user_id',
            'text': 'text'
        }

        self._comment_id = comment_id
        self._user_id = user_id
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def comment_id(self):
        """Gets the comment_id of this InlineResponse2002.


        :return: The comment_id of this InlineResponse2002.
        :rtype: int
        """
        return self._comment_id

    @comment_id.setter
    def comment_id(self, comment_id):
        """Sets the comment_id of this InlineResponse2002.


        :param comment_id: The comment_id of this InlineResponse2002.
        :type comment_id: int
        """

        self._comment_id = comment_id

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse2002.


        :return: The user_id of this InlineResponse2002.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse2002.


        :param user_id: The user_id of this InlineResponse2002.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def text(self):
        """Gets the text of this InlineResponse2002.


        :return: The text of this InlineResponse2002.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this InlineResponse2002.


        :param text: The text of this InlineResponse2002.
        :type text: str
        """

        self._text = text
