# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None):  # noqa: E501
        """InlineObject2 - a model defined in OpenAPI

        :param user_id: The user_id of this InlineObject2.  # noqa: E501
        :type user_id: int
        """
        self.openapi_types = {
            'user_id': int
        }

        self.attribute_map = {
            'user_id': 'user_id'
        }

        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_2 of this InlineObject2.  # noqa: E501
        :rtype: InlineObject2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this InlineObject2.


        :return: The user_id of this InlineObject2.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineObject2.


        :param user_id: The user_id of this InlineObject2.
        :type user_id: int
        """

        self._user_id = user_id
