# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject3(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, text=None):  # noqa: E501
        """InlineObject3 - a model defined in OpenAPI

        :param user_id: The user_id of this InlineObject3.  # noqa: E501
        :type user_id: int
        :param text: The text of this InlineObject3.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'user_id': int,
            'text': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'text': 'text'
        }

        self._user_id = user_id
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_3 of this InlineObject3.  # noqa: E501
        :rtype: InlineObject3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this InlineObject3.


        :return: The user_id of this InlineObject3.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineObject3.


        :param user_id: The user_id of this InlineObject3.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def text(self):
        """Gets the text of this InlineObject3.


        :return: The text of this InlineObject3.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this InlineObject3.


        :param text: The text of this InlineObject3.
        :type text: str
        """

        self._text = text
